# Generated by Django 4.2.7 on 2023-11-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="PRDCost",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="product",
            name="PRDPrice",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
