# Generated by Django 4.2.7 on 2023-11-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_prdcost_alter_product_prdprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="PRDCost",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="product",
            name="PRDPrice",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
