# Generated by Django 4.2.7 on 2023-11-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_prdcost_alter_product_prdprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="PRDCost",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Cost"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="PRDCreated",
            field=models.DateTimeField(verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="product",
            name="PRDDesc",
            field=models.TextField(verbose_name="Product Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="PRDName",
            field=models.CharField(max_length=50, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="PRDPrice",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Price"
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PRDIImage",
                    models.ImageField(upload_to="product/", verbose_name="Image"),
                ),
                (
                    "PRDIProduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Product",
                    ),
                ),
            ],
        ),
    ]
