# Generated by Django 4.2.7 on 2023-11-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_prdcost_alter_product_prdcreated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="PRDIImage",
            field=models.ImageField(upload_to="product_image/", verbose_name="Image"),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CATName", models.CharField(max_length=50)),
                ("CATDesc", models.TextField()),
                ("CATImg", models.ImageField(upload_to="category/")),
                (
                    "CATParent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
        ),
    ]
