# Generated by Django 4.2.7 on 2023-11-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_productimage_prdiimage_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="CATParent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"CATParent__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.category",
            ),
        ),
        migrations.CreateModel(
            name="Product_Alternative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PALNAlternative",
                    models.ManyToManyField(
                        related_name="alternative_product", to="product.product"
                    ),
                ),
                (
                    "PALNProduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_product",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Alternative",
                "verbose_name_plural": "Product Alternatives",
            },
        ),
    ]
