# Generated by Django 4.2.7 on 2023-11-30 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_category_options_alter_category_catparent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Accessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PACCAlternative",
                    models.ManyToManyField(
                        related_name="accessories_product", to="product.product"
                    ),
                ),
                (
                    "PACCProduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mainAccessory_product",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Accessory",
                "verbose_name_plural": "Product Accessories",
            },
        ),
    ]
