# Generated by Django 4.2.7 on 2023-11-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_product_accessories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="PRDCreated",
            field=models.DateTimeField(auto_now=True, verbose_name="Created at"),
        ),
    ]
