# Generated by Django 4.2.7 on 2023-12-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_alter_product_options_product_prddiscountprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="PRDISBestSeller",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="PRDISNew",
            field=models.BooleanField(default=True),
        ),
    ]
