# Generated by Django 4.2.7 on 2023-12-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_alter_product_prddiscountprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="CATSlug",
            field=models.SlugField(blank=True, null=True, verbose_name="Category URL"),
        ),
    ]
