# Generated by Django 4.2.7 on 2023-12-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_invoice_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_invoice_number", models.IntegerField(default=0)),
            ],
        ),
    ]
